### PR TITLE
Change the type of opening hours from string to slice

### PR DESCRIPTION
**Pull request by kevin-DL**

### CODE REVIEW

**Comment by asim** [comment]
Not the right place to make this change. This library is code generated.. please see github.com/micro/services

**Comment by kevin-DL** [comment]
I am not very familiar with protobut but it looks ok to me in services
https://github.com/micro/services/blob/3843df89ea969ef7e02eeb26160ad0180f32b7f9/place/proto/place.pb.go#L43

**Comment by asim** [comment]
It's defined in proto here https://github.com/micro/services/blob/master/place/proto/place.proto#L28

We can only modify the protobuf. We may have to remove it if its posing an issue and we can't correlate the type.

**Comment by asim** [comment]
I don't actually know why it's a string in the generated code

**Comment by kevin-DL** [comment]
OK. Thank you. It seems to have generated the Types field properly, so it's strange

**Comment by asim** [comment]
I'll try flip the fields and see if it kicks off new generation or something

**Comment by asim** [comment]
Otherwise its quite quirky

**Comment by kevin-DL** [comment]
OK. Thank you. I will wait to see if a newer version comes out.

**Comment by kevin-DL** [comment]
Good morning.
It does not look like it got updated.

**Comment by asim** [comment]
I have discovered exactly what is happening. For some reason, because the name "opening_hours" has an underscore, it seems to not understand that it's a repeated field e.g array. So there's something wrong with the openapi generated. I'll need to look at tit over the weekend.

**Comment by kevin-DL** [comment]
@asim Do you have any news about this? Anything i can do?

**Comment by asim** [comment]
So the generator is here https://github.com/m3o/m3o/tree/main/cmd/protoc-gen-openapi

For some reason when the field has an underscore in the name e.g opening_hours it drops the fact that this is repeated field and makes it a string instead, almost like its the default type if it can't find the info its looking for. I'm guessing this is totally down to the way its mapping that info and then trying to look it up. If you can look through this code and just see where that problem is occuring that would be helpful.

**Comment by kevin-DL** [comment]
I think the issue is here https://github.com/m3o/m3o/blob/012acf2d95af644cd6e2a6ac84e916a948dd5fbb/cmd/protoc-gen-openapi/converter/message.go#L225

For context
```go
message VerifyResponse {
	// Auth token to be saved into '~/.micro'
	// For users who are already registered and paid,
	// the flow stops here.
	// For users who are yet to be registered
	// the token will be acquired in the 'FinishSignup' step.
	AuthToken authToken = 1;
	// Payment provider custommer id that can be used to
	// acquire a payment method, see 'micro login' flow for more.
	// @todo this is likely not needed
	string customerID = 2;
	// Namespace to use
	// @todod deprecated since we no longer support OTP logins
	string namespace = 3;
	// Message to display to the user
	string message = 4;
	// Whether payment is required or not
	bool payment_required = 5;
	// Namespaces one has access to based on previous invites
	// Currently only 1 is supported
	repeated string namespaces = 6;
	// hoursOpening repeated string with an underscore in the name
	repeated string hours_opening = 7;
}
```

When we get to the line specified in message.go

`fieldName = HoursOpening` without the underscore
which means that `strings.ToLower(fieldName) = hoursopening` which is not `hours_opening` so `isList` is never updated.

Also we can't just add the underscore when the name of the field is capitalized because on line 218, the name is split on the underscore which would lead to a similar error i think.

**Comment by kevin-DL** [comment]
if  we change the if statement to

```go
if strings.ToLower(fieldName) == *desc.Name || strings.ToLower(fieldName) == strings.ReplaceAll(*desc.Name, "_", "") {
						isList = f.Desc.IsList()
						field = f
					}
```

it seems to work fine but i don't think that's ideal

**Comment by kevin-DL** [comment]
Thank you for looking into it.

**Pull request closed without merging**
